# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem.xci
# IP: The module: 'packet_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'packet_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem.xci
# IP: The module: 'packet_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'packet_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
