# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
read_ip /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem.xci
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top packet_mem -part xc7vx485tffg1761-2 -mode out_of_context
rename_ref -prefix_all packet_mem_
write_checkpoint -noxdef packet_mem.dcp
catch { report_utilization -file packet_mem_utilization_synth.rpt -pb packet_mem_utilization_synth.pb }
if { [catch {
  file copy -force /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.runs/packet_mem_synth_1/packet_mem.dcp /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /afs/ece.cmu.edu/usr/terencea/Public/18545/digitaldesign/src/work_vivado/first_draft/first_draft.srcs/sources_1/ip/packet_mem/packet_mem_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
